file = open('college_admission_list.txt', 'a')
file.write(input('Please provide student number: '))
file.write(', ')
file.write(input('Please provide full name: '))
file.write(', ')
file.write(input('Please provide birthdate (mm/dd/yyyy): '))
file.write(', ')
file.write(input('Please provide gender (M/F): ').upper())
file.write(', ')
file.write(input('Please provide address (do not use ","): '))
file.write(', ')
file.write(input('Please provide contact number: '))
file.write(', ')
file.write(input('Please provide course: '))
file.write('\n')
file.close()

print('\n\nFile updated successfully.')
